language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
install:
  - pip install -e .[test]
script:
  - pytest
deploy:
  provider: pypi
  user: debonzi
  password:
    secure: TnaU8EtbRwHUH+BoUAB3dFNAGJPAMe/iu3F/QN6x7LAMhGs5TjTegB7/Ajc6xPdNvEDIV3BhB+bPev9kX/rlI/iNhf4of3iPJ1cqPu7Ow3KocKV1ouBzcowgmASWxmqSporBzTx37OcX0IJ+jvJyLkBHQF5xwW8fBc3AlVJBQyd8BDVc9cyGflhSzfQ3X5T37SfQWZC9QeFEPpQC8Evk4PborPgn6LDeNKW/eH8FvIzNBZKd/XKPbD4iDlzUQr7pQP8xjf0LhzKot9RoYYkCSltNti7Tah0MQQ+iiAaN7G5/SD40HjEz+bZ+GHSmmXNEd/1rQXARJjiyjlsbmM1XsBTEuCH29kNmsQv9rr2eyDoiFTsmZAALSEh3Aiw9I4UBL8FPdwGWJGUxT/tATab/HakCsZz7HsRMM3Y6zFC9QjF4dMkTdHa52FvbMqwWACoHt8xR48W8SZ6mhzvjyVO+4Cr2PqpHCUcx9arxR9SbrWP9SUoHYRcrJRZGkVuBpBZHw4fdOJgJHMRnyaZrLLTgeWXLbvoEbrmnVFWy8SaylQ1Vzm9pTEE5+eQoaenIwRWFDQ86uj40JIlv/B2/wNojdiedCE36q01dDR704ieTIAgyFct0DhyYvLcB85eWO3inDh64rOotYdghWGKweVQxPoKHltQEbSubig8t2Ob5hlg=
  on:
    tags: true
    branch: master
    python: '3.6'
