language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
install:
  - pip install -e .[test]
script:
  - pytest
deploy:
  provider: pypi
  user: debonzi
  password:
    secure: YbW8HJGwVdJ52vMDWVC8ibiA+OxWFCjVUVMtfVbDcKH+89HUbXrZ6iWZ1Py3z7fSz6nPx2aqBWlY2TsiDlcbtJTwPIeXe3t/cU0o3FnNVREiXEYMX6qkASesX4lF+f99XBBf8UTxxpNfTMSGKBtRdUYfTORD9b+laGnfUNkuoDf8F/AkXDf3qpeVeFjJDgBtwEKMI8PUJUiGYIkrkarXVRy8nzz4wVQu86DkttEsVEDzv6K7CXl7RXLgi8xCiuOzwuJfuA3Gn3xjn/k9u4HXbjY1DcW+4zWArY3IH8NP7INmcjbj61/qloK9O5JkBVmyiLHCuWs9oWtS8wbk2+2PN0Dd/yYcGlJ+59KVzhGXeIYOqJbaT3+VuljQevKplbg8yhQsFwuj2XitNnQETDnbDGJWbz31dpKXgBpgmzaT9CgE6OtenvZsHQW9unQRS3LC55957f85M7YYgCJvKAKDfrEDBieamzDaSwDeUZ6kvaW5P+EJULEaWaiH9rYRBE4MGtjok5RBjxGbl9yb0ZKjigUrO4yntVRt7QL48ROs7MEqIhDRNuIxtjzcQxanda4v9ZHVfCK1wxDS5A0YY9HAsNakDmbsqFrbWOEJrVB4MHbWPruVJO7CIiAQNS5ZHOzwSxof/m15oDZV5stgWU+LxczN53AUiBOBSN7RMGTsxfI=
  on:
    tags: true
    branch: master
    python: '3.6'
